version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Usa la versión de Java que necesitas, aquí Java 11
    commands:
      - echo Installing SonarQube Scanner...

      - export SONAR_SCANNER_VERSION=6.0.0.4432
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
  pre_build:
    commands:
      - echo "Running pre-build phase..."
    
  build:
    commands:
     
      - echo "Running SonarQube scan..."
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=producto-service \
        -Dsonar.projectName='producto-service' \
        -Dsonar.host.url=https://5b7a-200-68-170-62.ngrok-free.app \
        -Dsonar.token=rubi
  post_build:
    commands:
      - echo "Build completed. Check SonarQube dashboard for results."
        
artifacts:
  files:
    - '**/*'
