version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Especifica la versión de Python si es necesario
    commands:
      # Instala el CLI de Fortify on Demand
      - echo "Instalando Fortify on Demand CLI..."
      #- curl -o fortify-cli.zip "https://tools.fortify.com/fortify-on-demand-cli.zip"
      - curl -o fortify-cli.zip "https://objects.githubusercontent.com/github-production-release-asset-2e65be/417134921/847d2de5-7954-4957-b5e1-5e0a753ad4ab?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240927%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240927T191333Z&X-Amz-Expires=300&X-Amz-Signature=dad548189bd988e0be85937c3fed3c2529820bece7259f684b6e711d5382922a&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dfcli-linux.tgz&response-content-type=application%2Foctet-stream" 
      
      - unzip fortify-cli.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/fodcli
      - export PATH=/usr/local/bin/:$PATH

  pre_build:
    commands:
      - echo Logging in to Fortify on Demand...
      - fodcli login --tenant montepiedad  --username Julio Ulises Rodriguez Muñoz --password Prueb@s24987
      - echo "Prepara la aplicación para el análisis..."
      - zip -r ~/mi_codigo.zip /usr/local/bin/

  build:
    commands:
      - echo "Subiendo el código a Fortify on Demand..."
      - fortify upload --file ~/mi_codigo.zip --project "OXXO" --version "PocFortify"

  post_build:
    commands:
      - echo "Ejecutando análisis en Fortify..."
      - fortify scan --project "OXXO" --version "PocFortify"

artifacts:
  files:
    - ~/mi_codigo.zip
